AUTH_UNSUPPORTED_MECHANISM = "504 5.7.4 Unsupported authentication mechanism"
AUTH_CREDENTIALS_MISSING = "535 5.7.8 Authentication credentials missing"
AUTH_INVALID_ENCODING = "535 5.7.8 Invalid authentication credentials encoding"
AUTH_FAILED = "535 5.7.8 Authentication failed"
AUTH_UNEXPECTED_ERROR = "554 5.7.0 Unexpected error during authentication"

SMTP_BARE_LF = "550 5.6.0 Message contains bare LF line endings"
SMTP_MISSING_FROM = "554 5.6.0 Missing required header: From"
SMTP_MISSING_DATE = "554 5.6.0 Missing required header: Date"
SMTP_INVALID_FROM = "554 5.6.0 Invalid From header"
SMTP_INVALID_DATE = "554 5.6.0 Invalid Date header"
SMTP_MALFORMED_ADDRESS = "553 5.1.3 Error: malformed address"
SMTP_AUTH_REQUIRED = "530 5.7.0 Authentication required"
SMTP_TRANSACTION_FAILED = "554 Transaction failed"
SMTP_OK = "250 OK"
SMTP_USER_NOT_LOCAL = "551 User not local"
SMTP_ACTION_ABORTED = "451 Action aborted"
SMTP_TLS_NOT_AVAILABLE = "454 4.7.0 TLS not available"
SMTP_RATE_LIMITED = "451 4.7.0 Rate limit exceeded, please retry later"
# Centralized SMTP response strings shared across modules.
